services:
  network-traffic-forecasting:
    build:
      dockerfile: ./forecasting/Dockerfile
    image: network-traffic-forecasting:latest
    container_name: network-traffic-forecasting
    hostname: network-traffic-forecasting
    restart: unless-stopped
    ports:
      - 8501:8501
      - 80:8501
    volumes:
      - ./forecasting:/app
      - ./datasets:/app/datasets
    stdin_open: false
    tty: false
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
